/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

// GetCondition of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicy of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) GetManagementPolicy() xpv1.ManagementPolicy {
	return mg.Spec.ManagementPolicy
}

// GetProviderConfigReference of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

/*
GetProviderReference of this VSphereOfflineSoftwareDepot.
Deprecated: Use GetProviderConfigReference.
*/
func (mg *VSphereOfflineSoftwareDepot) GetProviderReference() *xpv1.Reference {
	return mg.Spec.ProviderReference
}

// GetPublishConnectionDetailsTo of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// GetWriteConnectionSecretToReference of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicy of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) SetManagementPolicy(r xpv1.ManagementPolicy) {
	mg.Spec.ManagementPolicy = r
}

// SetProviderConfigReference of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

/*
SetProviderReference of this VSphereOfflineSoftwareDepot.
Deprecated: Use SetProviderConfigReference.
*/
func (mg *VSphereOfflineSoftwareDepot) SetProviderReference(r *xpv1.Reference) {
	mg.Spec.ProviderReference = r
}

// SetPublishConnectionDetailsTo of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// SetWriteConnectionSecretToReference of this VSphereOfflineSoftwareDepot.
func (mg *VSphereOfflineSoftwareDepot) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
