/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ComponentObservation struct {
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Version []*string `json:"version,omitempty" tf:"version,omitempty"`
}

type ComponentParameters struct {
}

type VSphereOfflineSoftwareDepotObservation struct {

	// The list of components in this depot.
	Component []ComponentObservation `json:"component,omitempty" tf:"component,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The remote location where the contents for this depot are served.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`
}

type VSphereOfflineSoftwareDepotParameters struct {

	// The remote location where the contents for this depot are served.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`
}

// VSphereOfflineSoftwareDepotSpec defines the desired state of VSphereOfflineSoftwareDepot
type VSphereOfflineSoftwareDepotSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VSphereOfflineSoftwareDepotParameters `json:"forProvider"`
}

// VSphereOfflineSoftwareDepotStatus defines the observed state of VSphereOfflineSoftwareDepot.
type VSphereOfflineSoftwareDepotStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VSphereOfflineSoftwareDepotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereOfflineSoftwareDepot is the Schema for the VSphereOfflineSoftwareDepots API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type VSphereOfflineSoftwareDepot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.location)",message="location is a required parameter"
	Spec   VSphereOfflineSoftwareDepotSpec   `json:"spec"`
	Status VSphereOfflineSoftwareDepotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VSphereOfflineSoftwareDepotList contains a list of VSphereOfflineSoftwareDepots
type VSphereOfflineSoftwareDepotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VSphereOfflineSoftwareDepot `json:"items"`
}

// Repository type metadata.
var (
	VSphereOfflineSoftwareDepot_Kind             = "VSphereOfflineSoftwareDepot"
	VSphereOfflineSoftwareDepot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VSphereOfflineSoftwareDepot_Kind}.String()
	VSphereOfflineSoftwareDepot_KindAPIVersion   = VSphereOfflineSoftwareDepot_Kind + "." + CRDGroupVersion.String()
	VSphereOfflineSoftwareDepot_GroupVersionKind = CRDGroupVersion.WithKind(VSphereOfflineSoftwareDepot_Kind)
)

func init() {
	SchemeBuilder.Register(&VSphereOfflineSoftwareDepot{}, &VSphereOfflineSoftwareDepotList{})
}
