apiVersion: networking.crossplane.io/v1alpha1
kind: VSphereHostPortGroup
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/vspherehostportgroup
  labels:
    testing.upbound.io/example-name: pg
  name: pg
spec:
  forProvider:
    hostSystemId: ${data.vsphere_host.host.id}
    name: portgroup-01
    virtualSwitchName: vSwitchTerraformTest

---

apiVersion: networking.crossplane.io/v1alpha1
kind: VSphereHostVirtualSwitch
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/vspherehostportgroup
  labels:
    testing.upbound.io/example-name: host_virtual_switch
  name: host-virtual-switch
spec:
  forProvider:
    activeNics:
    - vmnic0
    hostSystemId: ${data.vsphere_host.host.id}
    name: switch-01
    networkAdapters:
    - vmnic0
    - vmnic1
    standbyNics:
    - vmnic1
