apiVersion: hostandclustermanagement.crossplane.io/v1alpha1
kind: VSphereComputeClusterVmHostRule
metadata:
  annotations:
    meta.upbound.io/example-id: hostandclustermanagement/v1alpha1/vspherecomputeclustervmhostrule
  labels:
    testing.upbound.io/example-name: cluster_vm_host_rule
  name: cluster-vm-host-rule
spec:
  forProvider:
    affinityHostGroupName: terraform-test-cluster-host-group
    computeClusterId: ${data.vsphere_compute_cluster.cluster.id}
    name: terraform-test-cluster-vm-host-rule
    vmGroupName: terraform-test-cluster-vm-group

---

apiVersion: hostandclustermanagement.crossplane.io/v1alpha1
kind: VSphereComputeClusterHostGroup
metadata:
  annotations:
    meta.upbound.io/example-id: hostandclustermanagement/v1alpha1/vspherecomputeclustervmhostrule
  labels:
    testing.upbound.io/example-name: cluster_host_group
  name: cluster-host-group
spec:
  forProvider:
    computeClusterId: ${data.vsphere_compute_cluster.cluster.id}
    hostSystemIds:
    - ${data.vsphere_host.host.id}
    name: terraform-test-cluster-vm-group

---

apiVersion: hostandclustermanagement.crossplane.io/v1alpha1
kind: VSphereComputeClusterVmGroup
metadata:
  annotations:
    meta.upbound.io/example-id: hostandclustermanagement/v1alpha1/vspherecomputeclustervmhostrule
  labels:
    testing.upbound.io/example-name: cluster_vm_group
  name: cluster-vm-group
spec:
  forProvider:
    computeClusterId: ${data.vsphere_compute_cluster.cluster.id}
    name: terraform-test-cluster-vm-group
    virtualMachineIds:
    - ${vsphere_virtual_machine.vm.id}

---

apiVersion: virtualmachine.crossplane.io/v1alpha1
kind: VSphereVirtualMachine
metadata:
  annotations:
    meta.upbound.io/example-id: hostandclustermanagement/v1alpha1/vspherecomputeclustervmhostrule
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    datastoreIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vsphere_datastore
    disk:
    - label: disk0
      size: 20
    guestId: otherLinux64Guest
    memory: 2048
    name: terraform-test
    networkInterface:
    - networkId: ${data.vsphere_network.network.id}
    numCpus: 2
    resourcePoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vsphere_compute_cluster
