/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this VSphereSupervisor
func (mg *VSphereSupervisor) GetTerraformResourceType() string {
	return "vsphere_supervisor"
}

// GetConnectionDetailsMapping for this VSphereSupervisor
func (tr *VSphereSupervisor) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this VSphereSupervisor
func (tr *VSphereSupervisor) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this VSphereSupervisor
func (tr *VSphereSupervisor) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this VSphereSupervisor
func (tr *VSphereSupervisor) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this VSphereSupervisor
func (tr *VSphereSupervisor) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this VSphereSupervisor
func (tr *VSphereSupervisor) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this VSphereSupervisor using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *VSphereSupervisor) LateInitialize(attrs []byte) (bool, error) {
	params := &VSphereSupervisorParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *VSphereSupervisor) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this VSphereVirtualMachineClass
func (mg *VSphereVirtualMachineClass) GetTerraformResourceType() string {
	return "vsphere_virtual_machine_class"
}

// GetConnectionDetailsMapping for this VSphereVirtualMachineClass
func (tr *VSphereVirtualMachineClass) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this VSphereVirtualMachineClass
func (tr *VSphereVirtualMachineClass) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this VSphereVirtualMachineClass
func (tr *VSphereVirtualMachineClass) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this VSphereVirtualMachineClass
func (tr *VSphereVirtualMachineClass) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this VSphereVirtualMachineClass
func (tr *VSphereVirtualMachineClass) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this VSphereVirtualMachineClass
func (tr *VSphereVirtualMachineClass) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this VSphereVirtualMachineClass using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *VSphereVirtualMachineClass) LateInitialize(attrs []byte) (bool, error) {
	params := &VSphereVirtualMachineClassParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *VSphereVirtualMachineClass) GetTerraformSchemaVersion() int {
	return 0
}
